#!/usr/bin/env bash
#this script will display information about subdomains of my domain name
subdomain() {
	dig "$2.$1" |
		awk 'c&&!--c;/;; ANSWER SECTION:/{c=1}' |
		awk -v subdom="$2" '{ print "The subdomain " subdom " is a " $4 " record and points to " $5}'
	return 0
}

subdomains() {
	subdomains=("www" "lb-01" "web-01" "web-02")
	for subdomain in "${subdomains[@]}"
	do
		dig "$subdomain.$1" |
			awk 'c&&!--c;/;; ANSWER SECTION:/{c=1}' |
			awk -v subdom="$subdomain" '{ print "The subdomain " subdom " is a " $4 " record and points to " $5}'
	done
	return 0
}

if [ -z "$2" ]
then
	subdomains "$1"
else
	subdomain "$1" "$2"
fi
