#!/usr/bin/env bash
#this script updates the packages and installs nginx
sudo apt-get -y update && sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo bash -c "echo 'Hello World!'> /var/www/html/index.nginx-debian.html"
sudo service nginx start
