#!/usr/bin/env bash
# This script displays "Best School" but on th 9th iteration diplays hi also

for i in {1..10}
do
	if [ "$i" == 9 ]
	then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
done
