#!/usr/bin/env bash
# This script displays "Best School" but on th 9th iteration diplays hi also

count=1

while [ $count -le 10 ]
do
	if [ "$count" == 9 ]
	then
		echo "Best School"
		echo "Hi"
		(( count++ ))
	else
		echo "Best School"
		(( count++ ))
	fi
done
